### ISSUE TITLE
Questions about spliting dataset

### ISSUE THREAD

**Issue by JesseLi666** [bighuang624/DSANet#2]
Thanks for your code!

However, I have questions about spliting dataset. Supposing there are 10000 time steps data (10000 lines), and I want to split 60%, 20%, 20% as train, valid, test. So there will be 6000 lines in my train set. But I'm not sure in the valid set should there be 2000 lines or 6000+2000=8000 lines?

**Comment by bighuang624** [comment]
@JesseLi666  The first one.
