### ISSUE TITLE
single_cpu_trainer.py: error: argument --n_multiv: invalid int value: '{n_multiv}'

### ISSUE THREAD

**Issue by Josepharol** [bighuang624/DSANet#4]
Hello, 
 When I run this command,"python single_cpu_trainer.py --data_name {data_name} --n_multiv {n_multiv}", I receive the following output,  
--------------------------------------------------------------------------------
usage: single_cpu_trainer.py [-h] [--test_tube_save_path TEST_TUBE_SAVE_PATH]
                             [--model_save_path MODEL_SAVE_PATH]
                             [--local LOCAL] [--n_kernels N_KERNELS]
                             [-w_kernel W_KERNEL] [--d_model D_MODEL]
                             [--d_inner D_INNER] [--d_k D_K] [--d_v D_V]
                             [--n_head N_HEAD] [--n_layers N_LAYERS]
                             [--drop_prob DROP_PROB] [--data_name DATA_NAME]
                             [--data_dir DATA_DIR] [--n_multiv N_MULTIV]
                             [--window WINDOW] [--horizon HORIZON]
                             [--learning_rate LEARNING_RATE]
                             [--optimizer_name OPTIMIZER_NAME]
                             [--criterion CRITERION] [--batch_size BATCH_SIZE]
single_cpu_trainer.py: error: argument --n_multiv: invalid int value: '{n_multiv}'
--------------------------------------------------------------------------------

Then, I tried running only this command, "python single_cpu_trainer.py --data_name {data_name} ", my output is,
--------------------------------------------------------------------------------
RUNNING ON CPU
loading model...
model built
gpu available: False, used: False
tng data loader called
test data loader called
val data loader called
                                              Name  \
0                                             sgsf
1                                       sgsf.conv2
2                                   sgsf.in_linear
3                                  sgsf.out_linear
4                                 sgsf.layer_stack
5                               sgsf.layer_stack.0
6                      sgsf.layer_stack.0.slf_attn
7                 sgsf.layer_stack.0.slf_attn.w_qs
8                 sgsf.layer_stack.0.slf_attn.w_ks
9                 sgsf.layer_stack.0.slf_attn.w_vs
10           sgsf.layer_stack.0.slf_attn.attention
11   sgsf.layer_stack.0.slf_attn.attention.dropout
12   sgsf.layer_stack.0.slf_attn.attention.softmax
13          sgsf.layer_stack.0.slf_attn.layer_norm
14                  sgsf.layer_stack.0.slf_attn.fc
15             sgsf.layer_stack.0.slf_attn.dropout
16                      sgsf.layer_stack.0.pos_ffn
17                  sgsf.layer_stack.0.pos_ffn.w_1
18                  sgsf.layer_stack.0.pos_ffn.w_2
19           sgsf.layer_stack.0.pos_ffn.layer_norm
20              sgsf.layer_stack.0.pos_ffn.dropout
21                              sgsf.layer_stack.1
22                     sgsf.layer_stack.1.slf_attn
23                sgsf.layer_stack.1.slf_attn.w_qs
24                sgsf.layer_stack.1.slf_attn.w_ks
25                sgsf.layer_stack.1.slf_attn.w_vs
26           sgsf.layer_stack.1.slf_attn.attention
27   sgsf.layer_stack.1.slf_attn.attention.dropout
28   sgsf.layer_stack.1.slf_attn.attention.softmax
29          sgsf.layer_stack.1.slf_attn.layer_norm
..                                             ...
178  slsf.layer_stack.4.slf_attn.attention.softmax
179         slsf.layer_stack.4.slf_attn.layer_norm
180                 slsf.layer_stack.4.slf_attn.fc
181            slsf.layer_stack.4.slf_attn.dropout
182                     slsf.layer_stack.4.pos_ffn
183                 slsf.layer_stack.4.pos_ffn.w_1
184                 slsf.layer_stack.4.pos_ffn.w_2
185          slsf.layer_stack.4.pos_ffn.layer_norm
186             slsf.layer_stack.4.pos_ffn.dropout
187                             slsf.layer_stack.5
188                    slsf.layer_stack.5.slf_attn
189               slsf.layer_stack.5.slf_attn.w_qs
190               slsf.layer_stack.5.slf_attn.w_ks
191               slsf.layer_stack.5.slf_attn.w_vs
192          slsf.layer_stack.5.slf_attn.attention
193  slsf.layer_stack.5.slf_attn.attention.dropout
194  slsf.layer_stack.5.slf_attn.attention.softmax
195         slsf.layer_stack.5.slf_attn.layer_norm
196                 slsf.layer_stack.5.slf_attn.fc
197            slsf.layer_stack.5.slf_attn.dropout
198                     slsf.layer_stack.5.pos_ffn
199                 slsf.layer_stack.5.pos_ffn.w_1
200                 slsf.layer_stack.5.pos_ffn.w_2
201          slsf.layer_stack.5.pos_ffn.layer_norm
202             slsf.layer_stack.5.pos_ffn.dropout
203                                             ar
204                                      ar.linear
205                                      W_output1
206                                        dropout
207                                    active_func

                              Type    Params
0    Single_Global_SelfAttn_Module  18949696
1                           Conv2d      2080
2                           Linear     16896
3                           Linear     16416
4                       ModuleList  18914304
5                     EncoderLayer   3152384
6               MultiHeadAttention   1051648
7                           Linear    262656
8                           Linear    262656
9                           Linear    262656
10       ScaledDotProductAttention         0
11                         Dropout         0
12                         Softmax         0
13                       LayerNorm      1024
14                          Linear    262656
15                         Dropout         0
16         PositionwiseFeedForward   2100736
17                          Conv1d   1050624
18                          Conv1d   1049088
19                       LayerNorm      1024
20                         Dropout         0
21                    EncoderLayer   3152384
22              MultiHeadAttention   1051648
23                          Linear    262656
24                          Linear    262656
25                          Linear    262656
26       ScaledDotProductAttention         0
27                         Dropout         0
28                         Softmax         0
29                       LayerNorm      1024
..                             ...       ...
178                        Softmax         0
179                      LayerNorm      1024
180                         Linear    262656
181                        Dropout         0
182        PositionwiseFeedForward   2100736
183                         Conv1d   1050624
184                         Conv1d   1049088
185                      LayerNorm      1024
186                        Dropout         0
187                   EncoderLayer   3152384
188             MultiHeadAttention   1051648
189                         Linear    262656
190                         Linear    262656
191                         Linear    262656
192      ScaledDotProductAttention         0
193                        Dropout         0
194                        Softmax         0
195                      LayerNorm      1024
196                         Linear    262656
197                        Dropout         0
198        PositionwiseFeedForward   2100736
199                         Conv1d   1050624
200                         Conv1d   1049088
201                      LayerNorm      1024
202                        Dropout         0
203                             AR        65
204                         Linear        65
205                         Linear        65
206                        Dropout         0
207                           Tanh         0

[208 rows x 3 columns]
Traceback (most recent call last):
  File "single_cpu_trainer.py", line 102, in <module>
    main(hyperparams)
  File "single_cpu_trainer.py", line 70, in main
    trainer.fit(model)
  File "C:\Users\abish\anaconda3\envs\Python36\lib\site-packages\pytorch_lightning\models\trainer.py", line 567, in fit
    self.__run_pretrain_routine(model)
  File "C:\Users\abish\anaconda3\envs\Python36\lib\site-packages\pytorch_lightning\models\trainer.py", line 778, in __run_pretrain_routine
    self.validate(model, dataloader, self.nb_sanity_val_steps, ds_i)
  File "C:\Users\abish\anaconda3\envs\Python36\lib\site-packages\pytorch_lightning\models\trainer.py", line 438, in validate
    output = self.__validation_forward(model, data_batch, batch_i, dataloader_i)
  File "C:\Users\abish\anaconda3\envs\Python36\lib\site-packages\pytorch_lightning\models\trainer.py", line 402, in __validation_forward
    output = model.validation_step(*args)
  File "C:\Program Files (x86)\DSAnet\DSANet\model.py", line 267, in validation_step
    y_hat = self.forward(x)
  File "C:\Program Files (x86)\DSAnet\DSANet\model.py", line 217, in forward
    sgsf_output, *_ = self.sgsf(x)
  File "C:\Users\abish\anaconda3\envs\Python36\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Program Files (x86)\DSAnet\DSANet\model.py", line 58, in forward
    x = x.view(-1, self.w_kernel, self.window, self.n_multiv)
TypeError: view(): argument 'size' must be tuple of ints, but found element of type NoneType at pos 4
--------------------------------------------------------------------------------

My packages : 
# packages in environment at C:\Users\abish\anaconda3\envs\Python36:
#
# Name                    Version                   Build  Channel
absl-py                   0.9.0                    pypi_0    pypi
blas                      1.0                         mkl
cachetools                4.1.0                    pypi_0    pypi
certifi                   2020.4.5.1       py36h9f0ad1d_0    conda-forge
cffi                      1.14.0           py36h7a1dbc1_0
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.0.130                      0
freetype                  2.9.1                ha9979f8_1
future                    0.18.2                   pypi_0    pypi
google-auth               1.13.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
grpcio                    1.28.1                   pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.9                      pypi_0    pypi
imageio                   2.8.0                    pypi_0    pypi
intel-openmp              2020.0                      166
jpeg                      9b                   hb83a4c4_2
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.1.0                h56a325e_0
markdown                  3.2.1                    pypi_0    pypi
mkl                       2020.0                      166
mkl-service               2.3.0            py36hb782905_0
mkl_fft                   1.0.15           py36h14836fe_0
mkl_random                1.1.0            py36h675688f_0
ninja                     1.9.0            py36h74a9793_0
numpy                     1.16.4           py36hc71023c_0    conda-forge
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py36_0
pandas                    0.20.3           py36hce827b7_2    anaconda
pillow                    7.0.0            py36hcc1f983_0
pip                       20.0.2                   py36_1
protobuf                  3.11.3                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_0
python                    3.6.10               h9f7ef89_1
python-dateutil           2.8.1                      py_0    anaconda
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   1.2.0           py3.6_cuda100_cudnn7_1    pytorch
pytorch-lightning         0.4.6                    pypi_0    pypi
pytz                      2019.3                     py_0    anaconda
requests                  2.23.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
scikit-learn              0.20.2           py36h343c172_0
scipy                     1.4.1            py36h9439919_0
setuptools                46.1.3                   py36_0
six                       1.14.0                   py36_0
sqlite                    3.31.1               he774522_0
tb-nightly                1.15.0a20190708          pypi_0    pypi
tensorboard               2.2.0                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0.post3              pypi_0    pypi
test-tube                 0.6.9                    pypi_0    pypi
tk                        8.6.8                hfa6e2cd_0
torchvision               0.3.0              py36_cu100_1    pytorch
tqdm                      4.45.0                   pypi_0    pypi
urllib3                   1.25.8                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py36_0
wincertstore              0.2              py36h7fe50ca_0
xz                        5.2.4                h2fa13f4_4
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0.

Since, I am new to programming and python, I tried my best to find a solution to the bugs, but I was not able to figure it out. Any help would be appreciated. Thanks.

**Comment by bighuang624** [comment]
@Josepharol 
I think you should use `python single_cpu_trainer.py --data_name {data_name} --n_multiv {n_multiv}` and should not remove `--n_multiv`. Have you changed `{data_name}` and `{n_multiv}` to actual value, e.g., exchange and 8?

**Comment by Josepharol** [comment]
First of all, thank you for the response. I really appreciate it.
I actually didn't put the actual values. Now I changed the name according to your example.
Like, the folder with the dataset will be called "exchange" and the different datasets will be named as, "exchange_test","exchange_train","exchange_validation", and I will run the file like, `python single_cpu_trainer.py --data_name exchange --n_multiv 8`

Is this correct?

**Comment by bighuang624** [comment]
I think it should be almost right, but I can't remember the details. Please follow [https://github.com/bighuang624/DSANet/blob/master/data/README.md](https://github.com/bighuang624/DSANet/blob/master/data/README.md), and make sure that the actual value of {n_multiv} is consistent with your data file. For example, if the .txt file includes a matrix of size m * n, organized as [https://github.com/laiguokun/multivariate-time-series-data](https://github.com/laiguokun/multivariate-time-series-data), then the value of {n_multiv} should be equal to n. @Josepharol

**Comment by Josepharol** [comment]
@bighuang624 , Thank you for the clarification. I tried running it accordingly, Please find my .txt files. I have not attached the training file since its huge.
Files:
[electricity_validation.txt](https://github.com/bighuang624/DSANet/files/4484948/electricity_validation.txt)
[electricity_test.txt](https://github.com/bighuang624/DSANet/files/4484949/electricity_test.txt)
![image](https://user-images.githubusercontent.com/55325641/79415275-915cd180-7f72-11ea-80f1-78c2d1da8d19.png)

I found it has the matrix of form 26304*320, and I split the training file as 15782*320, test as 5261*320 and validation as 5261*320. According to this n=320
I run this code : 
`python single_cpu_trainer.py --data_name electricity --n_multiv 320` and i got the following error, 

RUNNING ON CPU
loading model...
model built
gpu available: False, used: False
tng data loader called
test data loader called
val data loader called
                                              Name  \
0                                             sgsf
1                                       sgsf.conv2
2                                   sgsf.in_linear
3                                  sgsf.out_linear
4                                 sgsf.layer_stack
5                               sgsf.layer_stack.0
6                      sgsf.layer_stack.0.slf_attn
7                 sgsf.layer_stack.0.slf_attn.w_qs
8                 sgsf.layer_stack.0.slf_attn.w_ks
9                 sgsf.layer_stack.0.slf_attn.w_vs
10           sgsf.layer_stack.0.slf_attn.attention
11   sgsf.layer_stack.0.slf_attn.attention.dropout
12   sgsf.layer_stack.0.slf_attn.attention.softmax
13          sgsf.layer_stack.0.slf_attn.layer_norm
14                  sgsf.layer_stack.0.slf_attn.fc
15             sgsf.layer_stack.0.slf_attn.dropout
16                      sgsf.layer_stack.0.pos_ffn
17                  sgsf.layer_stack.0.pos_ffn.w_1
18                  sgsf.layer_stack.0.pos_ffn.w_2
19           sgsf.layer_stack.0.pos_ffn.layer_norm
20              sgsf.layer_stack.0.pos_ffn.dropout
21                              sgsf.layer_stack.1
22                     sgsf.layer_stack.1.slf_attn
23                sgsf.layer_stack.1.slf_attn.w_qs
24                sgsf.layer_stack.1.slf_attn.w_ks
25                sgsf.layer_stack.1.slf_attn.w_vs
26           sgsf.layer_stack.1.slf_attn.attention
27   sgsf.layer_stack.1.slf_attn.attention.dropout
28   sgsf.layer_stack.1.slf_attn.attention.softmax
29          sgsf.layer_stack.1.slf_attn.layer_norm
..                                             ...
178  slsf.layer_stack.4.slf_attn.attention.softmax
179         slsf.layer_stack.4.slf_attn.layer_norm
180                 slsf.layer_stack.4.slf_attn.fc
181            slsf.layer_stack.4.slf_attn.dropout
182                     slsf.layer_stack.4.pos_ffn
183                 slsf.layer_stack.4.pos_ffn.w_1
184                 slsf.layer_stack.4.pos_ffn.w_2
185          slsf.layer_stack.4.pos_ffn.layer_norm
186             slsf.layer_stack.4.pos_ffn.dropout
187                             slsf.layer_stack.5
188                    slsf.layer_stack.5.slf_attn
189               slsf.layer_stack.5.slf_attn.w_qs
190               slsf.layer_stack.5.slf_attn.w_ks
191               slsf.layer_stack.5.slf_attn.w_vs
192          slsf.layer_stack.5.slf_attn.attention
193  slsf.layer_stack.5.slf_attn.attention.dropout
194  slsf.layer_stack.5.slf_attn.attention.softmax
195         slsf.layer_stack.5.slf_attn.layer_norm
196                 slsf.layer_stack.5.slf_attn.fc
197            slsf.layer_stack.5.slf_attn.dropout
198                     slsf.layer_stack.5.pos_ffn
199                 slsf.layer_stack.5.pos_ffn.w_1
200                 slsf.layer_stack.5.pos_ffn.w_2
201          slsf.layer_stack.5.pos_ffn.layer_norm
202             slsf.layer_stack.5.pos_ffn.dropout
203                                             ar
204                                      ar.linear
205                                      W_output1
206                                        dropout
207                                    active_func

                              Type    Params
0    Single_Global_SelfAttn_Module  18949696
1                           Conv2d      2080
2                           Linear     16896
3                           Linear     16416
4                       ModuleList  18914304
5                     EncoderLayer   3152384
6               MultiHeadAttention   1051648
7                           Linear    262656
8                           Linear    262656
9                           Linear    262656
10       ScaledDotProductAttention         0
11                         Dropout         0
12                         Softmax         0
13                       LayerNorm      1024
14                          Linear    262656
15                         Dropout         0
16         PositionwiseFeedForward   2100736
17                          Conv1d   1050624
18                          Conv1d   1049088
19                       LayerNorm      1024
20                         Dropout         0
21                    EncoderLayer   3152384
22              MultiHeadAttention   1051648
23                          Linear    262656
24                          Linear    262656
25                          Linear    262656
26       ScaledDotProductAttention         0
27                         Dropout         0
28                         Softmax         0
29                       LayerNorm      1024
..                             ...       ...
178                        Softmax         0
179                      LayerNorm      1024
180                         Linear    262656
181                        Dropout         0
182        PositionwiseFeedForward   2100736
183                         Conv1d   1050624
184                         Conv1d   1049088
185                      LayerNorm      1024
186                        Dropout         0
187                   EncoderLayer   3152384
188             MultiHeadAttention   1051648
189                         Linear    262656
190                         Linear    262656
191                         Linear    262656
192      ScaledDotProductAttention         0
193                        Dropout         0
194                        Softmax         0
195                      LayerNorm      1024
196                         Linear    262656
197                        Dropout         0
198        PositionwiseFeedForward   2100736
199                         Conv1d   1050624
200                         Conv1d   1049088
201                      LayerNorm      1024
202                        Dropout         0
203                             AR        65
204                         Linear        65
205                         Linear        65
206                        Dropout         0
207                           Tanh         0

[208 rows x 3 columns]
Traceback (most recent call last):
  File "single_cpu_trainer.py", line 102, in <module>
    main(hyperparams)
  File "single_cpu_trainer.py", line 70, in main
    trainer.fit(model)
  File "C:\Users\abish\anaconda3\envs\Python36\lib\site-packages\pytorch_lightning\models\trainer.py", line 567, in fit
    self.__run_pretrain_routine(model)
  File "C:\Users\abish\anaconda3\envs\Python36\lib\site-packages\pytorch_lightning\models\trainer.py", line 778, in __run_pretrain_routine
    self.validate(model, dataloader, self.nb_sanity_val_steps, ds_i)
  File "C:\Users\abish\anaconda3\envs\Python36\lib\site-packages\pytorch_lightning\models\trainer.py", line 438, in validate
    output = self.__validation_forward(model, data_batch, batch_i, dataloader_i)
  File "C:\Users\abish\anaconda3\envs\Python36\lib\site-packages\pytorch_lightning\models\trainer.py", line 402, in __validation_forward
    output = model.validation_step(*args)
  File "C:\Program Files (x86)\DSAnet\DSANet\model.py", line 267, in validation_step
    y_hat = self.forward(x)
  File "C:\Program Files (x86)\DSAnet\DSANet\model.py", line 217, in forward
    sgsf_output, *_ = self.sgsf(x)
  File "C:\Users\abish\anaconda3\envs\Python36\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Program Files (x86)\DSAnet\DSANet\model.py", line 58, in forward
    x = x.view(-1, self.w_kernel, self.window, self.n_multiv)
RuntimeError: shape '[-1, 1, 64, 320]' is invalid for input of size 328704

I think I am doing it the right way according to your guidance, still its not running. Am I doing it correct?

**Comment by bighuang624** [comment]
@Josepharol  I think you get the wrong n value. The n value of electricity dataset is 321, as shown in the Table 1 of the paper [Modeling Long- and Short-Term Temporal Patterns with Deep Neural Networks](https://arxiv.org/pdf/1703.07015.pdf). And you will find it correct when n=321 and batch_size=16, as 16 * 1 * 64 * 321 = 328704.

**Comment by Josepharol** [comment]
Thank you @bighuang624 ,the code is running right now. However, its been running for almost 5days now. 
This is the last line of the running command on the command prompt now, 

> 22%| | 284/1308 [3:14:08<10:58:13, 38.61s/it, CORR=nan, MAE=187, RRSE=0.0899, batch_nb=285, epoch=9, tng_loss=2340617.443, v_nb=13, val_loss=2.25e+6]

Any idea how long it'll run or is there any termination condition for the code?

**Comment by bighuang624** [comment]
@Josepharol  Well, as we use Transformer, which may be seen as a heavy model, a large amount of calculation and long calculation time are required. For large datasets like electricity, such cost may be intolerable. Moreover, our method is proposed for dynamic-period or nonperiodic series. So if you just want to find a quick solution for your time series dataset, maybe you can try other traditional methods.
You can use CTRL+C to stop the program, or I guess it will be stopped by the EarlyStopping, but I'm not sure because I can not clearly remember it.

**Comment by Josepharol** [comment]
@bighuang624 , Okay, I get it now. Thank you for your support and clear explanations. I really appreciate it.

**Comment by Josepharol** [comment]
Hello Kyon,
 I tried to run th
[image: image.png]
e code with a smaller dataset and the result was the following. Where is
the prediction file attached after the code is executed?
